version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo:/data/db

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data

  kafgo:
    build: ./kafgo
    ports:
      - '8080:8080'
    environment:
      DB_URL: postgres://user:password@postgres:5432/db
      REDIS_URL: redis://redis:6379
      KAFKA: localhost:9092

  kafjs:
    build: ./kafjs
    ports:
      - '3000:3000'
    environment:
      MONGO_URL: mongodb://mongo:27017
      KAFKA: localhost:9092
      REDIS_URL: redis://redis:6379

  kafpy:
    build: ./kafpy
    ports:
      - '5000:5000'
    environment:
      MONGO_URL: mongodb://mongo:27017
      KAFKA: localhost:9092
      REDIS_URL: redis://redis:6379