version: '3.7'
services:
  client:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './client:/usr/share/nginx/html'
    depends_on:
      - server
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db